repository_type: pipeline

nf_core_version: 3.4.1

lint:
  files_unchanged:
    - .prettierignore
    - CODE_OF_CONDUCT.md
    - assets/nf-core-mg-assembler_logo_light.png
    - docs/images/nf-core-mg-assembler_logo_light.png
    - docs/images/nf-core-mg-assembler_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
    - .prettierignore
    - .prettierignore
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config:
    - report_comment
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - CODE_OF_CONDUCT.md
    - assets/nf-core-mg-assembler_logo_light.png
    - docs/images/nf-core-mg-assembler_logo_light.png
    - docs/images/nf-core-mg-assembler_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - assets/email_template.html
    - assets/sendmail_template.txt
    - assets/email_template.txt

template:
  org: nxf-csp
  name: mg-assembler
  description: Assembler for metagenomic data
  author: D. Poberezhniy, K. Baybekov
  version: 1.0.0dev
  force: true
  outdir: /raid/kbajbekov/common_share/github/nxf-csp/
  skip_features:
    - igenomes
    - seqera_platform
    - gpu
    - rocrate
    - email
    - adaptivecard
  is_nfcore: false
